<center> <h2>Ejercicio 01</h2> </center> 

* Crear un array 7x8 lleno de ceros de tipo entero.
* Crear un array 7x8 lleno de ceros salvo la primera fila que serán todo unos.
* Crear un array 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 8.

### 1.1. Crear un array 7x8 lleno de ceros de tipo entero 

In [1]:
import numpy as np 

a = np.zeros((7,8), dtype=np.int64)
print(a)
print()
print('El tipo de ceros son enteros: ')
print(a.dtype)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

El tipo de ceros son enteros: 
int64


### 1.2. Crear un array 7x8 lleno de ceros salvo la primera fila que seran todos unos

In [2]:
a = np.zeros((7,8))
a[0]=[1]
print(a)

#LINK DE AYUDA: https://www.desarrollo-web-br-bd.com/es/python/modificar-una-fila-columna-particular-de-una-matriz-numpy/1050692629/

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


### 1.3. Crear un array 7x8 lleno de ceros salvo la ultima fila que sera el rango entre 5 y 8

In [3]:
b = np.zeros((7,8))
b[6] = np.arange(5,13)
print(b)

#LINK DE AYUDA: https://cocalc.com/share/public_paths/970e563dcd94ae99676d86f768c0df52b7712b9e

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 5.  6.  7.  8.  9. 10. 11. 12.]]
